### PR TITLE
Nodes summary

### PR DESCRIPTION
**Pull request by AdamsGH**
Hey! Here is a little improvement to add /nodes endpoint with some code refactoring for this needs. Also add ghcr registry build workflow. I hope this can solve issue from #28, at least that's my case.

Here is a little summary:
1. Added build_ghcr.yaml for GitHub Container Registry workflow.
2. Included a Helm chart in the helm directory for easier deployment.
3. Updated main.go:
	- Added a new /nodes endpoint to retrieve metrics for all nodes in the cluster.
	- Improved error handling and context management.
4. Updated main_test.go with new tests for the added functionality.
5. Updated README.md:
6. Added information about the new /nodes endpoint.
	- Included details about command-line flags and available metrics.

### CODE REVIEW

**Comment by george-angel** [comment]
Hello @AdamsGH - sorry I was on leave.

Can you please explain more about your use-case and why you need a new endpoint for collecting summary from all Nodes?

Thanks!

**Comment by george-angel** [comment]
Thanks for explaining.

Have you seen the scrape config example we provide (linked in the README) https://github.com/utilitywarehouse/kube-summary-exporter/blob/master/manifests/scrape-config.yaml ?

This is what we use ourselves. Our largest production cluster is 170 Nodes and >1700 PVCs. For this we run a single replica Deployment and its only using 30Mi memory. This way we leave the Node discovery to Prometheus. I think that sits neatly where it should.

This way when you go to Prometheus UI and check "Targets" you will see an endpoint per Node, and you get `instance` label assigned by Prometheus.

2024-11-01-150819_2560x363_scrot

Would this work for you?

**Comment by AdamsGH** [comment]
Yeah, I saw it, look really good. But unfortunately our whole system is fundamentally built on service monitors, so adding scrape configs in our case is not an option at least for now =(

**Comment by george-angel** [comment]
I see!

In that case I'm happy to accept a new `/nodes` endpoint to address this use-case. However:

- I don't believe we need the GHCR build - we already have a build and push images to Quay.
- Helm - we don't use Helm, and I don't want to take on the maintenance of this.

**Comment by AdamsGH** [comment]
I'm glad to hear that! Rolled back unnecessary commits and left only main part

**Comment by george-angel** [comment]
Thanks @AdamsGH !

I'm sorry I have pushed some changes since you opened the PR to fix bugs I found while reviewing. Could you please resolve conflicts?

I'm just getting a few more people to cast their eyes over your changes to see if I missed anything :+1:

**Review by asiyani — APPROVED** [review]
small request, could you please add some fake node data to `test-summary.prom` file so that node labels in the test is not empty string.
apart from that all good. :+1:
Thank you for the PR!

**Review by asiyani — APPROVED** [review]

**Pull request merged**
