### PR TITLE
Add some new metrics for pod ephemeral storage 

### PR DESCRIPTION
**Pull request by superbrothers**
This PR adds some new metrics for pod ephemeral storage.

    - `kube_summary_pod_ephemeral_storage_available_bytes`: Number of bytes of Ephemeral storage that aren't consumed by the pod
    - `kube_summary_pod_ephemeral_storage_capacity_bytes`: Number of bytes of Ephemeral storage that can be consumed by the pod
    - `kube_summary_pod_ephemeral_storage_used_bytes`: Number of bytes of Ephemeral storage that are consumed by the pod
    - `kube_summary_pod_ephemeral_storage_inodes_free`: Number of available Inodes for pod Ephemeral storage
    - `kube_summary_pod_ephemeral_storage_inodes`: Number of Inodes for pod Ephemeral storage
    - `kube_summary_pod_ephemeral_storage_inodes_used`: Number of used Inodes for pod Ephemeral storage

### CODE REVIEW

**Comment by superbrothers** [comment]
@ribbybibby Could you review this PR?

**Review by ribbybibby — CHANGES_REQUESTED** [review]
Hi @superbrothers. Thanks for the contribution! It looks good.

A few things:
- Can you move the manifests to a separate PR? I'd like to review those separately.
- Could you implement the `inodes` metrics, like we do for the other fsstats?

**Comment by superbrothers** [comment]
I've moved sample manifest files to #6.

**Comment by superbrothers** [comment]
> Could you implement the inodes metrics, like we do for the other fsstats?

Yes, but I'm going to do it in a different PR.

**Comment by ribbybibby** [comment]
> Yes, but I'm going to do it in a different PR.

How come? Seems like it would fit into this one.

**Comment by superbrothers** [comment]
I misread your comment:bow:

I have added the following metrics:

- `kube_summary_pod_ephemeral_storage_inodes_free`: Number of available Inodes for pod Ephemeral storage
- `kube_summary_pod_ephemeral_storage_inodes`: Number of Inodes for pod Ephemeral storage
- `kube_summary_pod_ephemeral_storage_inodes_used`: Number of used Inodes for pod Ephemeral storage

**Review by ribbybibby — APPROVED** [review]

**Pull request merged**
